[2025-02-04T14:06:39.789+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:06:39.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:06:39.795+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:39.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:06:39.922+0000] {processor.py:925} INFO - DAG(s) 'simple_dag' retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:06:40.838+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:40.834+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:simple_dag
[2025-02-04T14:06:41.032+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:41.029+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:simple_dag
[2025-02-04T14:06:41.083+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:41.082+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:simple_dag
[2025-02-04T14:06:41.131+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:41.130+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:simple_dag
[2025-02-04T14:06:41.172+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:41.171+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:simple_dag
[2025-02-04T14:06:41.190+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:41.189+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:simple_dag
[2025-02-04T14:06:41.217+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:41.216+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:simple_dag
[2025-02-04T14:06:41.224+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:41.224+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T14:06:41.288+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:41.288+0000] {dag.py:3262} INFO - Creating ORM DAG for simple_dag
[2025-02-04T14:06:41.418+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:06:41.418+0000] {dag.py:4180} INFO - Setting next_dagrun for simple_dag to 2025-02-03 00:00:00+00:00, run_after=2025-02-04 00:00:00+00:00
[2025-02-04T14:06:41.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 1.751 seconds
[2025-02-04T14:08:19.341+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:08:19.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:08:19.358+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:08:19.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:08:19.406+0000] {processor.py:925} INFO - DAG(s) 'simple_dag' retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:08:19.514+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:08:19.513+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T14:08:19.672+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:08:19.671+0000] {dag.py:4180} INFO - Setting next_dagrun for simple_dag to 2025-02-03 00:00:00+00:00, run_after=2025-02-04 00:00:00+00:00
[2025-02-04T14:08:19.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.453 seconds
[2025-02-04T14:08:50.541+0000] {processor.py:186} INFO - Started process (PID=211) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:08:50.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:08:50.548+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:08:50.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:08:50.575+0000] {processor.py:925} INFO - DAG(s) 'simple_dag' retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:08:50.612+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:08:50.611+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T14:08:50.655+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:08:50.655+0000] {dag.py:4180} INFO - Setting next_dagrun for simple_dag to 2025-02-03 00:00:00+00:00, run_after=2025-02-04 00:00:00+00:00
[2025-02-04T14:08:50.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.161 seconds
[2025-02-04T14:09:21.018+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:09:21.020+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:09:21.024+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:09:21.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:09:21.078+0000] {processor.py:925} INFO - DAG(s) 'simple_dag' retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:09:21.127+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:09:21.126+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T14:09:21.172+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:09:21.171+0000] {dag.py:4180} INFO - Setting next_dagrun for simple_dag to 2025-02-03 00:00:00+00:00, run_after=2025-02-04 00:00:00+00:00
[2025-02-04T14:09:21.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.205 seconds
[2025-02-04T14:09:51.517+0000] {processor.py:186} INFO - Started process (PID=338) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:09:51.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:09:51.524+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:09:51.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:09:51.563+0000] {processor.py:925} INFO - DAG(s) 'simple_dag' retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:09:51.612+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:09:51.612+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T14:09:51.663+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:09:51.663+0000] {dag.py:4180} INFO - Setting next_dagrun for simple_dag to 2025-02-03 00:00:00+00:00, run_after=2025-02-04 00:00:00+00:00
[2025-02-04T14:09:51.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.207 seconds
[2025-02-04T14:10:21.963+0000] {processor.py:186} INFO - Started process (PID=402) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:10:22.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:10:22.013+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:10:22.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:10:22.069+0000] {processor.py:925} INFO - DAG(s) 'simple_dag' retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:10:22.192+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:10:22.191+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T14:10:22.357+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:10:22.356+0000] {dag.py:4180} INFO - Setting next_dagrun for simple_dag to 2025-02-03 00:00:00+00:00, run_after=2025-02-04 00:00:00+00:00
[2025-02-04T14:10:22.687+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.756 seconds
[2025-02-04T14:10:55.845+0000] {processor.py:186} INFO - Started process (PID=456) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:10:55.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:10:55.860+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:10:55.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:10:55.899+0000] {processor.py:925} INFO - DAG(s) 'simple_dag' retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:10:55.935+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:10:55.934+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T14:10:56.005+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:10:56.004+0000] {dag.py:4180} INFO - Setting next_dagrun for simple_dag to 2025-02-03 00:00:00+00:00, run_after=2025-02-04 00:00:00+00:00
[2025-02-04T14:10:56.046+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.225 seconds
[2025-02-04T14:11:29.266+0000] {processor.py:186} INFO - Started process (PID=509) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:11:29.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:11:29.278+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:11:29.277+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:11:29.309+0000] {processor.py:925} INFO - DAG(s) 'simple_dag' retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:11:29.362+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:11:29.361+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T14:11:29.425+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:11:29.424+0000] {dag.py:4180} INFO - Setting next_dagrun for simple_dag to 2025-02-04 00:00:00+00:00, run_after=2025-02-05 00:00:00+00:00
[2025-02-04T14:11:29.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.221 seconds
[2025-02-04T14:18:26.941+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:18:26.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:18:26.948+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:18:26.948+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:18:27.027+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:18:26.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import main as main
ModuleNotFoundError: No module named 'main'
[2025-02-04T14:18:27.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:18:27.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.295 seconds
[2025-02-04T14:18:37.009+0000] {processor.py:186} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:18:37.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:18:37.015+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:18:37.014+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:18:37.048+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:18:37.040+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import main as main
ModuleNotFoundError: No module named 'main'
[2025-02-04T14:18:37.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:18:37.133+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:18:37.132+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'simple_dag', 'Task Id': 'print_hello', 'Run Id': 'manual__2025-02-04T14:11:11.445268+00:00', 'Hostname': 'e92bdc463866', 'External Executor Id': '5cf3a4e0-5807-4353-b404-967b712ae599'}
[2025-02-04T14:18:37.183+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T14:18:37.184+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 14:11:39.925546+00:00 end:2025-02-04 14:18:37.182397+00:00 duration:417.256851
[2025-02-04T14:18:37.185+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): print_hello> dag:<DAG: simple_dag> dagrun:<DagRun simple_dag @ 2025-02-04 14:11:11.445268+00:00: manual__2025-02-04T14:11:11.445268+00:00, state:running, queued_at: 2025-02-04 14:11:11.491146+00:00. externally triggered: True>
[2025-02-04T14:18:37.186+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'simple_dag', 'Task Id': 'print_hello', 'Run Id': 'manual__2025-02-04T14:11:11.445268+00:00', 'Hostname': 'e92bdc463866', 'External Executor Id': '5cf3a4e0-5807-4353-b404-967b712ae599'}
[2025-02-04T14:18:37.187+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:18:37.187+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_dag, task_id=print_hello, run_id=manual__2025-02-04T14:11:11.445268+00:00, execution_date=20250204T141111, start_date=20250204T141139, end_date=20250204T141837
[2025-02-04T14:18:37.230+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:18:37.230+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: simple_dag.print_hello manual__2025-02-04T14:11:11.445268+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T14:18:37.239+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:18:37.238+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'simple_dag', 'Task Id': 'print_hello', 'Run Id': 'scheduled__2025-02-03T00:00:00+00:00', 'Hostname': 'e92bdc463866', 'External Executor Id': '700d78b3-451d-4d59-94c8-700a4c3b814c'}
[2025-02-04T14:18:37.259+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T14:18:37.260+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 14:11:39.963654+00:00 end:2025-02-04 14:18:37.259074+00:00 duration:417.29542
[2025-02-04T14:18:37.261+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): print_hello> dag:<DAG: simple_dag> dagrun:<DagRun simple_dag @ 2025-02-03 00:00:00+00:00: scheduled__2025-02-03T00:00:00+00:00, state:running, queued_at: 2025-02-04 14:11:10.532892+00:00. externally triggered: False>
[2025-02-04T14:18:37.262+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'simple_dag', 'Task Id': 'print_hello', 'Run Id': 'scheduled__2025-02-03T00:00:00+00:00', 'Hostname': 'e92bdc463866', 'External Executor Id': '700d78b3-451d-4d59-94c8-700a4c3b814c'}
[2025-02-04T14:18:37.263+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:18:37.263+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_dag, task_id=print_hello, run_id=scheduled__2025-02-03T00:00:00+00:00, execution_date=20250203T000000, start_date=20250204T141139, end_date=20250204T141837
[2025-02-04T14:18:37.275+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:18:37.274+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: simple_dag.print_hello scheduled__2025-02-03T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T14:18:37.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.279 seconds
[2025-02-04T14:19:07.971+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:07.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:07.978+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:07.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:08.006+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:08.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import main as main
ModuleNotFoundError: No module named 'main'
[2025-02-04T14:19:08.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:08.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.108 seconds
[2025-02-04T14:19:19.660+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:19.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:19.668+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:19.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:19.735+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:19.725+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import mai
ModuleNotFoundError: No module named 'main'
[2025-02-04T14:19:19.750+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:19.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.149 seconds
[2025-02-04T14:19:20.684+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:20.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:20.692+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:20.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:20.726+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:20.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    import 
           ^
SyntaxError: invalid syntax
[2025-02-04T14:19:20.728+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:20.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.111 seconds
[2025-02-04T14:19:34.310+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:34.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:34.314+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:34.314+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:34.476+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:34.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    from import
    ^^^^^^^^^^
NameError: name 'fromimport' is not defined
[2025-02-04T14:19:34.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:34.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.342 seconds
[2025-02-04T14:19:35.762+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:35.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:35.768+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:35.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:35.797+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:35.794+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from simport 
                 ^
SyntaxError: invalid syntax
[2025-02-04T14:19:35.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:35.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.085 seconds
[2025-02-04T14:19:38.635+0000] {processor.py:186} INFO - Started process (PID=206) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:38.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:38.639+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:38.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:38.665+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:38.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from scriptimport 
                      ^
SyntaxError: invalid syntax
[2025-02-04T14:19:38.666+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:38.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.103 seconds
[2025-02-04T14:19:39.418+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:39.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:39.421+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:39.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:39.453+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:39.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from script import 
                       ^
SyntaxError: invalid syntax
[2025-02-04T14:19:39.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:39.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.083 seconds
[2025-02-04T14:19:41.072+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:41.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:41.267+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:41.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:41.328+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:41.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from script. import 
                 ^^^^^^
SyntaxError: invalid syntax
[2025-02-04T14:19:41.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:41.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.316 seconds
[2025-02-04T14:19:43.149+0000] {processor.py:186} INFO - Started process (PID=233) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:43.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:43.159+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:43.157+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:43.254+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:43.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from script. #import 
                 ^^^^^^^^^
SyntaxError: invalid syntax
[2025-02-04T14:19:43.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:43.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.161 seconds
[2025-02-04T14:19:45.221+0000] {processor.py:186} INFO - Started process (PID=238) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:45.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:45.230+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:45.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:45.260+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:45.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from script.import 
                ^^^^^^
SyntaxError: invalid syntax
[2025-02-04T14:19:45.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:45.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.087 seconds
[2025-02-04T14:19:46.984+0000] {processor.py:186} INFO - Started process (PID=244) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:46.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:47.001+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:46.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:47.033+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:47.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from scripts. import 
                  ^^^^^^
SyntaxError: invalid syntax
[2025-02-04T14:19:47.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:47.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.103 seconds
[2025-02-04T14:19:51.688+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:51.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:51.692+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:51.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:51.717+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:51.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from scripts.iimport 
                         ^
SyntaxError: invalid syntax
[2025-02-04T14:19:51.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:51.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.114 seconds
[2025-02-04T14:19:52.986+0000] {processor.py:186} INFO - Started process (PID=265) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:52.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:52.992+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:52.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:53.071+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:53.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from scripts.ingesimport 
                             ^
SyntaxError: invalid syntax
[2025-02-04T14:19:53.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:53.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.238 seconds
[2025-02-04T14:19:54.011+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:54.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:54.017+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:54.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:54.087+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:54.085+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from scripts.ingestdatimport 
                                 ^
SyntaxError: invalid syntax
[2025-02-04T14:19:54.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:54.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.142 seconds
[2025-02-04T14:19:55.042+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:55.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:55.051+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:55.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:55.114+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:55.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from scripts.ingestdata import 
                                   ^
SyntaxError: invalid syntax
[2025-02-04T14:19:55.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:55.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.190 seconds
[2025-02-04T14:19:57.422+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:19:57.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:19:57.427+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:57.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:57.469+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:19:57.466+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from scripts.ingestdata import  
                                    ^
SyntaxError: invalid syntax
[2025-02-04T14:19:57.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:19:57.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.110 seconds
[2025-02-04T14:20:19.056+0000] {processor.py:186} INFO - Started process (PID=316) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:20:19.061+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:20:19.064+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:19.063+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:19.145+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:19.141+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from scripts.ingestdata   
                              ^
SyntaxError: invalid syntax
[2025-02-04T14:20:19.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:19.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.223 seconds
[2025-02-04T14:20:23.863+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:20:23.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:20:23.870+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:23.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:23.919+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:23.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    from scripts.ingestdata   
                              ^
SyntaxError: invalid syntax
[2025-02-04T14:20:23.924+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:24.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.182 seconds
[2025-02-04T14:20:25.950+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:20:25.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:20:25.955+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:25.954+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:26.005+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:26.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    im scripts.ingestdata   
       ^^^^^^^
SyntaxError: invalid syntax
[2025-02-04T14:20:26.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:26.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.162 seconds
[2025-02-04T14:20:27.000+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:20:27.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:20:27.006+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:27.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:27.199+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:27.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:20:27.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:27.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.280 seconds
[2025-02-04T14:20:38.866+0000] {processor.py:186} INFO - Started process (PID=345) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:20:38.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:20:38.870+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:38.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:38.893+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:38.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    import scripts.ingestdata  as 
                                  ^
SyntaxError: invalid syntax
[2025-02-04T14:20:38.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:38.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.075 seconds
[2025-02-04T14:20:39.992+0000] {processor.py:186} INFO - Started process (PID=346) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:20:39.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:20:39.996+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:39.995+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:40.023+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:40.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9
    import scripts.ingestdata  as  
                                   ^
SyntaxError: invalid syntax
[2025-02-04T14:20:40.024+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:40.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.078 seconds
[2025-02-04T14:20:47.435+0000] {processor.py:186} INFO - Started process (PID=352) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:20:47.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:20:47.452+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:47.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:47.585+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:47.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:20:47.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:47.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.339 seconds
[2025-02-04T14:20:54.767+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:20:54.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:20:54.772+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:54.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:54.796+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:20:54.795+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 76
    script.
           ^
SyntaxError: invalid syntax
[2025-02-04T14:20:54.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:20:54.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.074 seconds
[2025-02-04T14:21:04.595+0000] {processor.py:186} INFO - Started process (PID=412) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:21:04.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:21:04.601+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:04.600+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:04.678+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:04.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:21:04.682+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:04.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.137 seconds
[2025-02-04T14:21:05.712+0000] {processor.py:186} INFO - Started process (PID=413) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:21:05.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:21:05.717+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:05.716+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:05.747+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:05.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 76
    script.
           ^
SyntaxError: invalid syntax
[2025-02-04T14:21:05.749+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:05.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.090 seconds
[2025-02-04T14:21:10.883+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:21:10.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:21:10.888+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:10.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:10.971+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:10.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:21:10.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:11.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.150 seconds
[2025-02-04T14:21:11.964+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:21:11.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:21:11.968+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:11.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:12.025+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:12.012+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:21:12.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:12.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.126 seconds
[2025-02-04T14:21:12.151+0000] {processor.py:186} INFO - Started process (PID=416) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:21:12.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:21:12.154+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:12.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:12.468+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:12.348+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:21:12.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:12.632+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.490 seconds
[2025-02-04T14:21:12.846+0000] {processor.py:186} INFO - Started process (PID=417) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:21:12.851+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:21:12.872+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:12.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:13.537+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:13.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 76
    script.
           ^
SyntaxError: invalid syntax
[2025-02-04T14:21:13.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:13.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.858 seconds
[2025-02-04T14:21:13.997+0000] {processor.py:186} INFO - Started process (PID=418) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:21:14.001+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:21:14.005+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:14.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:14.092+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:14.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:21:14.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:14.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.163 seconds
[2025-02-04T14:21:14.262+0000] {processor.py:186} INFO - Started process (PID=419) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:21:14.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:21:14.272+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:14.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:14.317+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:14.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:21:14.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:14.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.169 seconds
[2025-02-04T14:21:14.466+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:21:14.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:21:14.469+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:14.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:15.123+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:15.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:21:15.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:15.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.755 seconds
[2025-02-04T14:21:46.075+0000] {processor.py:186} INFO - Started process (PID=485) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:21:46.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:21:46.080+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:46.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:46.141+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:21:46.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:21:46.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:21:46.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.159 seconds
[2025-02-04T14:22:04.935+0000] {processor.py:186} INFO - Started process (PID=549) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:04.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:04.981+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:04.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:05.075+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:05.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:05.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:05.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.205 seconds
[2025-02-04T14:22:06.225+0000] {processor.py:186} INFO - Started process (PID=550) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:06.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:06.230+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:06.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:06.306+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:06.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:06.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:06.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.143 seconds
[2025-02-04T14:22:09.355+0000] {processor.py:186} INFO - Started process (PID=551) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:09.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:09.360+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:09.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:09.430+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:09.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:09.433+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:09.465+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.125 seconds
[2025-02-04T14:22:10.590+0000] {processor.py:186} INFO - Started process (PID=552) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:10.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:10.594+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:10.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:10.640+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:10.637+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 15
    fetch_erp_task=
                   ^
SyntaxError: invalid syntax
[2025-02-04T14:22:10.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:10.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.124 seconds
[2025-02-04T14:22:11.716+0000] {processor.py:186} INFO - Started process (PID=553) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:11.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:11.720+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:11.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:11.783+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:11.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:11.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:11.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.124 seconds
[2025-02-04T14:22:13.870+0000] {processor.py:186} INFO - Started process (PID=554) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:13.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:13.878+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:13.877+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:13.907+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:13.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 15
    fetch_erp_task=script.
                          ^
SyntaxError: invalid syntax
[2025-02-04T14:22:13.909+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:13.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.085 seconds
[2025-02-04T14:22:14.039+0000] {processor.py:186} INFO - Started process (PID=555) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:14.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:14.067+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:14.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:14.110+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:14.108+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 15
    fetch_erp_task=script.
                          ^
SyntaxError: invalid syntax
[2025-02-04T14:22:14.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:14.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.128 seconds
[2025-02-04T14:22:16.160+0000] {processor.py:186} INFO - Started process (PID=556) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:16.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:16.166+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:16.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:16.216+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:16.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:16.218+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:16.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.100 seconds
[2025-02-04T14:22:17.327+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:17.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:17.330+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:17.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:17.379+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:17.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:17.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:17.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.095 seconds
[2025-02-04T14:22:17.504+0000] {processor.py:186} INFO - Started process (PID=558) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:17.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:17.512+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:17.511+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:17.568+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:17.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:17.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:17.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.139 seconds
[2025-02-04T14:22:37.227+0000] {processor.py:186} INFO - Started process (PID=622) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:37.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:37.232+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:37.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:37.296+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:37.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:37.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:37.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.119 seconds
[2025-02-04T14:22:39.275+0000] {processor.py:186} INFO - Started process (PID=623) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:39.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:39.279+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:39.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:39.321+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:39.316+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:39.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:39.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.091 seconds
[2025-02-04T14:22:42.346+0000] {processor.py:186} INFO - Started process (PID=624) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:42.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:42.350+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:42.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:42.402+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:42.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:42.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:42.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.105 seconds
[2025-02-04T14:22:57.159+0000] {processor.py:186} INFO - Started process (PID=641) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:22:57.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:22:57.164+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:57.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:57.224+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:22:57.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:22:57.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:22:57.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.117 seconds
[2025-02-04T14:23:00.046+0000] {processor.py:186} INFO - Started process (PID=653) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:23:00.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:23:00.052+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:23:00.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:23:00.133+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:23:00.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:23:00.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:23:00.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.175 seconds
[2025-02-04T14:23:30.880+0000] {processor.py:186} INFO - Started process (PID=717) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:23:30.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:23:30.884+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:23:30.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:23:30.904+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:23:30.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:23:30.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:23:30.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.082 seconds
[2025-02-04T14:24:01.133+0000] {processor.py:186} INFO - Started process (PID=780) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:24:01.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:24:01.137+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:24:01.137+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:24:01.169+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:24:01.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:24:01.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:24:01.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.079 seconds
[2025-02-04T14:24:34.096+0000] {processor.py:186} INFO - Started process (PID=833) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:24:34.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:24:34.128+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:24:34.119+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:24:34.553+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:24:34.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:24:34.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:24:34.672+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.648 seconds
[2025-02-04T14:31:42.420+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:31:42.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:31:42.433+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:31:42.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:31:42.480+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:31:42.469+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:31:42.486+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:31:42.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.190 seconds
[2025-02-04T14:33:06.464+0000] {processor.py:186} INFO - Started process (PID=146) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:33:06.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:33:06.472+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:33:06.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:33:06.521+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:33:06.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:33:06.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:33:06.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.138 seconds
[2025-02-04T14:33:36.693+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:33:36.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:33:36.700+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:33:36.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:33:36.726+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:33:36.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:33:36.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:33:36.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.082 seconds
[2025-02-04T14:34:07.355+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:34:07.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:34:07.363+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:34:07.362+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:34:07.388+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:34:07.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:34:07.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:34:07.434+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.099 seconds
[2025-02-04T14:34:38.249+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:34:38.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:34:38.254+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:34:38.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:34:38.281+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:34:38.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:34:38.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:34:38.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.089 seconds
[2025-02-04T14:35:09.149+0000] {processor.py:186} INFO - Started process (PID=394) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:35:09.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:35:09.165+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:35:09.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:35:09.210+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:35:09.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:35:09.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:35:09.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.127 seconds
[2025-02-04T14:35:39.897+0000] {processor.py:186} INFO - Started process (PID=456) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:35:39.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:35:39.903+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:35:39.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:35:39.970+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:35:39.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:35:39.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:35:40.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.133 seconds
[2025-02-04T14:36:11.243+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:36:11.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:36:11.275+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:36:11.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:36:11.358+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:36:11.342+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:36:11.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:36:11.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.288 seconds
[2025-02-04T14:36:46.635+0000] {processor.py:186} INFO - Started process (PID=577) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:36:46.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:36:46.641+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:36:46.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:36:46.664+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:36:46.658+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:36:46.665+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:36:46.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.080 seconds
[2025-02-04T14:37:17.752+0000] {processor.py:186} INFO - Started process (PID=637) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:37:17.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:37:17.762+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:37:17.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:37:17.789+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:37:17.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:37:17.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:37:17.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.090 seconds
[2025-02-04T14:37:50.902+0000] {processor.py:186} INFO - Started process (PID=689) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:37:50.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:37:50.912+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:37:50.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:37:50.940+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:37:50.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:37:50.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:37:50.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.118 seconds
[2025-02-04T14:38:21.110+0000] {processor.py:186} INFO - Started process (PID=752) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:38:21.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:38:21.117+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:38:21.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:38:21.142+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:38:21.136+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:38:21.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:38:21.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.105 seconds
[2025-02-04T14:38:53.284+0000] {processor.py:186} INFO - Started process (PID=805) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:38:53.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:38:53.294+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:38:53.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:38:53.470+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:38:53.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:38:53.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:38:53.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.312 seconds
[2025-02-04T14:39:23.688+0000] {processor.py:186} INFO - Started process (PID=870) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:39:23.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:39:23.694+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:39:23.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:39:23.717+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:39:23.711+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:39:23.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:39:23.749+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.070 seconds
[2025-02-04T14:39:53.990+0000] {processor.py:186} INFO - Started process (PID=932) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:39:53.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:39:53.996+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:39:53.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:39:54.021+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:39:54.016+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:39:54.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:39:54.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.076 seconds
[2025-02-04T14:40:24.532+0000] {processor.py:186} INFO - Started process (PID=997) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:40:24.534+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:40:24.550+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:40:24.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:40:24.598+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:40:24.590+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:40:24.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:40:24.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.179 seconds
[2025-02-04T14:40:55.642+0000] {processor.py:186} INFO - Started process (PID=1061) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:40:55.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:40:55.658+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:40:55.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:40:55.832+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:40:55.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:40:55.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:40:55.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.303 seconds
[2025-02-04T14:41:26.771+0000] {processor.py:186} INFO - Started process (PID=1125) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:41:26.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:41:26.782+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:41:26.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:41:26.830+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:41:26.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:41:26.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:41:26.899+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.147 seconds
[2025-02-04T14:41:57.054+0000] {processor.py:186} INFO - Started process (PID=1189) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:41:57.056+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:41:57.061+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:41:57.060+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:41:57.094+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:41:57.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:41:57.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:41:57.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.085 seconds
[2025-02-04T14:42:27.342+0000] {processor.py:186} INFO - Started process (PID=1253) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:42:27.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:42:27.349+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:42:27.348+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:42:27.370+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:42:27.366+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:42:27.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:42:27.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.076 seconds
[2025-02-04T14:42:57.534+0000] {processor.py:186} INFO - Started process (PID=1317) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:42:57.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:42:57.539+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:42:57.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:42:57.565+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:42:57.559+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:42:57.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:42:57.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.086 seconds
[2025-02-04T14:43:28.091+0000] {processor.py:186} INFO - Started process (PID=1381) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:43:28.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:43:28.098+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:43:28.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:43:28.130+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:43:28.121+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:43:28.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:43:28.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.101 seconds
[2025-02-04T14:43:58.539+0000] {processor.py:186} INFO - Started process (PID=1445) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:43:58.541+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:43:58.553+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:43:58.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:43:58.584+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:43:58.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:43:58.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:43:58.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.119 seconds
[2025-02-04T14:44:29.393+0000] {processor.py:186} INFO - Started process (PID=1509) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:44:29.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:44:29.402+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:44:29.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:44:29.446+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:44:29.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:44:29.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:44:29.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.166 seconds
[2025-02-04T14:45:00.286+0000] {processor.py:186} INFO - Started process (PID=1573) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:45:00.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:45:00.292+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:45:00.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:45:00.316+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:45:00.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:45:00.318+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:45:00.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.082 seconds
[2025-02-04T14:45:30.565+0000] {processor.py:186} INFO - Started process (PID=1637) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:45:30.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:45:30.571+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:45:30.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:45:30.909+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:45:30.833+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:45:30.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:45:30.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.415 seconds
[2025-02-04T14:46:01.407+0000] {processor.py:186} INFO - Started process (PID=1700) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:46:01.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:46:01.416+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:46:01.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:46:01.497+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:46:01.456+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:46:01.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:46:01.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.171 seconds
[2025-02-04T14:48:55.120+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:48:55.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:48:55.143+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:48:55.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:48:55.207+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:48:55.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:48:55.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:48:55.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.307 seconds
[2025-02-04T14:49:32.731+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:49:32.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:49:32.738+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:49:32.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:49:32.763+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:49:32.757+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:49:32.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:49:32.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.078 seconds
[2025-02-04T14:50:03.478+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:50:03.480+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:50:03.485+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:50:03.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:50:03.516+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:50:03.509+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:50:03.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:50:03.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.098 seconds
[2025-02-04T14:50:33.739+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:50:33.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:50:33.745+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:50:33.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:50:33.773+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:50:33.767+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:50:33.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:50:33.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.078 seconds
[2025-02-04T14:51:06.696+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:51:06.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:51:06.702+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:51:06.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:51:06.729+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:51:06.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:51:06.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:51:06.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.095 seconds
[2025-02-04T14:51:39.855+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:51:39.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:51:39.921+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:51:39.920+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:51:40.402+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:51:40.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:51:40.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:51:41.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 1.655 seconds
[2025-02-04T14:52:38.760+0000] {processor.py:186} INFO - Started process (PID=437) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:52:38.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:52:38.803+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:38.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:52:38.920+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:38.890+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:52:38.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:52:39.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.362 seconds
[2025-02-04T14:52:46.199+0000] {processor.py:186} INFO - Started process (PID=464) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:52:46.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:52:46.205+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:46.204+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:52:46.275+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:46.266+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:52:46.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:52:46.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.133 seconds
[2025-02-04T14:52:49.538+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:52:49.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:52:49.556+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:49.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:52:49.778+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:49.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:52:49.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:52:49.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.374 seconds
[2025-02-04T14:52:56.589+0000] {processor.py:186} INFO - Started process (PID=477) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:52:56.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:52:56.595+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:56.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:52:56.656+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:56.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:52:56.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:52:56.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.116 seconds
[2025-02-04T14:52:59.204+0000] {processor.py:186} INFO - Started process (PID=481) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:52:59.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:52:59.210+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:59.210+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:52:59.260+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:59.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:52:59.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:52:59.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.106 seconds
[2025-02-04T14:52:59.973+0000] {processor.py:186} INFO - Started process (PID=485) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:52:59.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:52:59.987+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:52:59.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:00.044+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:00.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:53:00.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:00.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.205 seconds
[2025-02-04T14:53:04.086+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:53:04.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:53:04.093+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:04.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:04.145+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:04.136+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 9, in <module>
    import scripts.ingestdata  as script
ModuleNotFoundError: No module named 'scripts.ingestdata'
[2025-02-04T14:53:04.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:04.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.105 seconds
[2025-02-04T14:53:18.621+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:53:18.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:53:18.628+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:18.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:18.670+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:18.664+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:53:18.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:18.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.100 seconds
[2025-02-04T14:53:38.525+0000] {processor.py:186} INFO - Started process (PID=567) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:53:38.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:53:38.556+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:38.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:38.621+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:38.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:53:38.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:38.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.147 seconds
[2025-02-04T14:53:42.351+0000] {processor.py:186} INFO - Started process (PID=574) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:53:42.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:53:42.361+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:42.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:42.401+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:42.399+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 18
    from
        ^
SyntaxError: invalid syntax
[2025-02-04T14:53:42.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:42.482+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.146 seconds
[2025-02-04T14:53:52.759+0000] {processor.py:186} INFO - Started process (PID=607) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:53:52.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:53:52.765+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:52.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:52.801+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:52.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 18
    from 
         ^
SyntaxError: invalid syntax
[2025-02-04T14:53:52.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:52.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.120 seconds
[2025-02-04T14:53:52.953+0000] {processor.py:186} INFO - Started process (PID=608) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:53:52.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:53:52.961+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:52.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:52.990+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:52.987+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 18
    from 
         ^
SyntaxError: invalid syntax
[2025-02-04T14:53:52.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:53.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.095 seconds
[2025-02-04T14:53:53.111+0000] {processor.py:186} INFO - Started process (PID=609) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:53:53.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:53:53.116+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:53.115+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:53.137+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:53:53.136+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 18
    from 
         ^
SyntaxError: invalid syntax
[2025-02-04T14:53:53.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:53:53.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.063 seconds
[2025-02-04T14:54:20.554+0000] {processor.py:186} INFO - Started process (PID=664) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:54:20.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:54:20.585+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:20.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:20.709+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:20.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 18
    from in
         ^^
SyntaxError: invalid syntax
[2025-02-04T14:54:20.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:20.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.284 seconds
[2025-02-04T14:54:22.279+0000] {processor.py:186} INFO - Started process (PID=666) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:54:22.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:54:22.317+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:22.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:22.390+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:22.388+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 18
    from ingest
               ^
SyntaxError: invalid syntax
[2025-02-04T14:54:22.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:22.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.316 seconds
[2025-02-04T14:54:27.620+0000] {processor.py:186} INFO - Started process (PID=675) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:54:27.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:54:27.650+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:27.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:27.694+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:27.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 18
    from ingestdata
                   ^
SyntaxError: invalid syntax
[2025-02-04T14:54:27.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:27.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.176 seconds
[2025-02-04T14:54:30.549+0000] {processor.py:186} INFO - Started process (PID=680) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:54:30.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:54:30.558+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:30.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:30.607+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:30.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 18
    from ingestdata i
                    ^
SyntaxError: invalid syntax
[2025-02-04T14:54:30.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:30.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.150 seconds
[2025-02-04T14:54:31.469+0000] {processor.py:186} INFO - Started process (PID=685) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:54:31.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:54:31.478+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:31.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:31.516+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:31.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 18
    from ingestdata impo
                    ^^^^
SyntaxError: invalid syntax
[2025-02-04T14:54:31.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:31.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.170 seconds
[2025-02-04T14:54:33.166+0000] {processor.py:186} INFO - Started process (PID=690) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:54:33.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:54:33.172+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:33.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:33.194+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:33.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 18
    from ingestdata import 
                           ^
SyntaxError: invalid syntax
[2025-02-04T14:54:33.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:33.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.067 seconds
[2025-02-04T14:54:48.870+0000] {processor.py:186} INFO - Started process (PID=724) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:54:48.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:54:48.876+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:48.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:48.932+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:54:48.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:54:48.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:54:48.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.107 seconds
[2025-02-04T14:55:04.525+0000] {processor.py:186} INFO - Started process (PID=755) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:55:04.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:55:04.534+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:55:04.533+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:55:04.586+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:55:04.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:55:04.589+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:55:04.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.139 seconds
[2025-02-04T14:55:19.552+0000] {processor.py:186} INFO - Started process (PID=789) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:55:19.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:55:19.562+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:55:19.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:55:19.614+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:55:19.602+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:55:19.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:55:19.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.136 seconds
[2025-02-04T14:55:21.541+0000] {processor.py:186} INFO - Started process (PID=798) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:55:21.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:55:21.549+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:55:21.548+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:55:21.605+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:55:21.597+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:55:21.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:55:21.636+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.104 seconds
[2025-02-04T14:55:21.708+0000] {processor.py:186} INFO - Started process (PID=799) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:55:21.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:55:21.715+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:55:21.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:55:21.752+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:55:21.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:55:21.755+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:55:21.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.091 seconds
[2025-02-04T14:55:21.858+0000] {processor.py:186} INFO - Started process (PID=800) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:55:21.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:55:21.863+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:55:21.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:55:21.894+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:55:21.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:55:21.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:55:21.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.081 seconds
[2025-02-04T14:56:01.806+0000] {processor.py:186} INFO - Started process (PID=864) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:56:01.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:56:01.827+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:56:01.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:56:01.873+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:56:01.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:56:01.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:56:01.919+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.147 seconds
[2025-02-04T14:56:32.439+0000] {processor.py:186} INFO - Started process (PID=925) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:56:32.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:56:32.469+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:56:32.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:56:32.501+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:56:32.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:56:32.504+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:56:32.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.149 seconds
[2025-02-04T14:57:03.604+0000] {processor.py:186} INFO - Started process (PID=989) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:57:03.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:57:03.610+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:57:03.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:57:03.644+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:57:03.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:57:03.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:57:03.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.098 seconds
[2025-02-04T14:57:33.812+0000] {processor.py:186} INFO - Started process (PID=1053) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:57:33.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:57:33.819+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:57:33.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:57:33.843+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:57:33.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:57:33.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:57:33.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.076 seconds
[2025-02-04T14:58:04.035+0000] {processor.py:186} INFO - Started process (PID=1111) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:58:04.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:58:04.044+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:58:04.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:58:04.078+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:58:04.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:58:04.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:58:04.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.105 seconds
[2025-02-04T14:58:34.271+0000] {processor.py:186} INFO - Started process (PID=1176) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:58:34.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:58:34.276+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:58:34.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:58:34.307+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:58:34.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:58:34.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:58:34.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.077 seconds
[2025-02-04T14:59:05.124+0000] {processor.py:186} INFO - Started process (PID=1241) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:59:05.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:59:05.131+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:59:05.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:59:05.170+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:59:05.160+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:59:05.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:59:05.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.112 seconds
[2025-02-04T14:59:38.221+0000] {processor.py:186} INFO - Started process (PID=1305) to work on /opt/airflow/dags/dag1.py
[2025-02-04T14:59:38.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T14:59:38.227+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:59:38.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T14:59:38.254+0000] {logging_mixin.py:190} INFO - [2025-02-04T14:59:38.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T14:59:38.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T14:59:38.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.084 seconds
[2025-02-04T15:00:08.400+0000] {processor.py:186} INFO - Started process (PID=1367) to work on /opt/airflow/dags/dag1.py
[2025-02-04T15:00:08.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T15:00:08.407+0000] {logging_mixin.py:190} INFO - [2025-02-04T15:00:08.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T15:00:08.434+0000] {logging_mixin.py:190} INFO - [2025-02-04T15:00:08.427+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T15:00:08.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T15:00:08.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.106 seconds
[2025-02-04T15:00:39.073+0000] {processor.py:186} INFO - Started process (PID=1427) to work on /opt/airflow/dags/dag1.py
[2025-02-04T15:00:39.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T15:00:39.083+0000] {logging_mixin.py:190} INFO - [2025-02-04T15:00:39.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T15:00:39.161+0000] {logging_mixin.py:190} INFO - [2025-02-04T15:00:39.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T15:00:39.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T15:00:39.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.163 seconds
[2025-02-04T15:01:11.130+0000] {processor.py:186} INFO - Started process (PID=1491) to work on /opt/airflow/dags/dag1.py
[2025-02-04T15:01:11.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T15:01:11.136+0000] {logging_mixin.py:190} INFO - [2025-02-04T15:01:11.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T15:01:11.162+0000] {logging_mixin.py:190} INFO - [2025-02-04T15:01:11.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T15:01:11.164+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T15:01:11.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.077 seconds
[2025-02-04T15:01:46.339+0000] {processor.py:186} INFO - Started process (PID=1554) to work on /opt/airflow/dags/dag1.py
[2025-02-04T15:01:46.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2025-02-04T15:01:46.359+0000] {logging_mixin.py:190} INFO - [2025-02-04T15:01:46.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2025-02-04T15:01:46.426+0000] {logging_mixin.py:190} INFO - [2025-02-04T15:01:46.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 11, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2025-02-04T15:01:46.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2025-02-04T15:01:46.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag1.py took 0.216 seconds
